name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-versions: [3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,test]

      - name: pytest
        run: |
          pytest . --verbose

      - name: list files
        run: ls -l .

      - uses: codecov/codecov-action@v3
        with:
          flags: "${{ matrix.os }} - ${{ matrix.python-versions }}"
          fail_ci_if_error: true
          files: coverage.xml
